version: '3'

services:
  express-app:
    container_name: project2_expressapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - node_modules:/app/node_modules
    depends_on:
      - mongo

  soap-app:
    container_name: soapapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    entrypoint: node soap-server.js
    volumes:
      - node_modules:/app/node_modules

  mongo:
    container_name: project2_mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ~/mongo-data:/data/db

volumes:
  mongo-data:
  node_modules:
